#!/usr/bin/env pwsh
# package_cmake.ps1 — Create the source-only CMake package (microlog-style).
# Package name: OpenLibCLI-<version>-cmake
# Output layout:
#   install/OpenLibCLI-<version>-cmake/
#     include/OpenLibCLI/          <- public headers
#     lib/cmake/OpenLibCLI/        <- Config, ConfigVersion files
#     share/OpenLibCLI/src/        <- source files
#     LICENSE, README.md, version

pushd $PSScriptRoot/../..

try {
    $VERSION = (Get-Content ./version).Trim()
    $PKG_NAME = "OpenLibCLI-$VERSION-cmake"
    $INSTALL_DIR = "install/$PKG_NAME"
    if (Test-Path $INSTALL_DIR) { Remove-Item -Path $INSTALL_DIR -Recurse -Force }

    # Create directory structure
    New-Item -ItemType Directory -Path "$INSTALL_DIR/include/OpenLibCLI/config" -Force | Out-Null
    New-Item -ItemType Directory -Path "$INSTALL_DIR/lib/cmake/OpenLibCLI" -Force | Out-Null
    New-Item -ItemType Directory -Path "$INSTALL_DIR/share/OpenLibCLI/src" -Force | Out-Null

    # Copy headers (preserving config/ subdir)
    Copy-Item -Path "cli/cli.h", "cli/cli_version.h", "cli/cli_env_detect.h" `
        -Destination "$INSTALL_DIR/include/OpenLibCLI/"
    Copy-Item -Path "cli/config/cli_config.h", "cli/config/cli_embedded_config.h" `
        -Destination "$INSTALL_DIR/include/OpenLibCLI/config/"

    # Copy sources
    Copy-Item -Path "cli/cli.c" `
        -Destination "$INSTALL_DIR/share/OpenLibCLI/src/"

    # Generate openlibcliConfig.cmake
    $configContent = @"
# Generated by package_cmake.ps1
get_filename_component(PACKAGE_PREFIX_DIR "`${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

macro(set_and_check _var _file)
  set(`${_var} "`${_file}")
  if(NOT EXISTS "`${_file}")
    message(FATAL_ERROR "File or directory `${_file} referenced by variable `${_var} does not exist !")
  endif()
endmacro()

macro(check_required_components _NAME)
  foreach(comp `${_NAME}_FIND_COMPONENTS)
    if(NOT `${_NAME}_`${comp}_FOUND)
      if(`${_NAME}_FIND_REQUIRED_`${comp})
        set(`${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()

get_filename_component(_OPENLIBCLI_DIR "`${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

set(openlibcli_VERSION "$VERSION")

add_library(OpenLibCLI STATIC
    "`${_OPENLIBCLI_DIR}/share/OpenLibCLI/src/cli.c"
)
target_include_directories(OpenLibCLI PUBLIC "`${_OPENLIBCLI_DIR}/include/OpenLibCLI")

if(WIN32)
    target_link_libraries(OpenLibCLI PUBLIC ws2_32)
endif()

add_library(OpenLibCLI::OpenLibCLI ALIAS OpenLibCLI)

check_required_components(OpenLibCLI)

"@
    Set-Content -Path "$INSTALL_DIR/lib/cmake/OpenLibCLI/openlibcliConfig.cmake" -Value $configContent -Encoding ascii

    # Generate openlibcliConfigVersion.cmake
    $versionContent = @"
# Generated by package_cmake.ps1
set(PACKAGE_VERSION "$VERSION")

if("`${PACKAGE_FIND_VERSION}" VERSION_EQUAL "${VERSION}")
  set(PACKAGE_VERSION_EXACT TRUE)
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
endif()

if("`${PACKAGE_FIND_VERSION}" VERSION_LESS "${VERSION}")
  if("`${PACKAGE_FIND_VERSION_MAJOR}" EQUAL "${VERSION.Split('.')[0]}")
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
  endif()
endif()

"@
    Set-Content -Path "$INSTALL_DIR/lib/cmake/OpenLibCLI/openlibcliConfigVersion.cmake" -Value $versionContent -Encoding ascii

    # Copy examples as reference (shared + serial + telnet only)
    New-Item -ItemType Directory -Path "$INSTALL_DIR/examples/shared" -Force | Out-Null
    New-Item -ItemType Directory -Path "$INSTALL_DIR/examples/win_linux/serial" -Force | Out-Null
    New-Item -ItemType Directory -Path "$INSTALL_DIR/examples/win_linux/telnet" -Force | Out-Null
    Copy-Item -Path "examples/shared/*" -Destination "$INSTALL_DIR/examples/shared/" -Force
    Copy-Item -Path "examples/win_linux/serial/*" -Destination "$INSTALL_DIR/examples/win_linux/serial/" -Force
    Copy-Item -Path "examples/win_linux/telnet/*" -Destination "$INSTALL_DIR/examples/win_linux/telnet/" -Force

    # Generate examples/CMakeLists.txt (standalone build, finds the package via find_package)
    $examplesCmake = @"
cmake_minimum_required(VERSION 3.14)
project(OpenLibCLI-examples C)
set(CMAKE_C_STANDARD 99)
set(CMAKE_C_STANDARD_REQUIRED ON)

find_package(OpenLibCLI REQUIRED)

add_executable(cli_server_serial
    win_linux/serial/cli_server_serial.c
    win_linux/serial/cli_transport_serial.c
    shared/cli_demo_setup.c
)
target_link_libraries(cli_server_serial PRIVATE OpenLibCLI::OpenLibCLI)

add_executable(cli_server_telnet
    win_linux/telnet/cli_server_telnet.c
    win_linux/telnet/cli_transport_telnet.c
    shared/cli_demo_setup.c
)
target_link_libraries(cli_server_telnet PRIVATE OpenLibCLI::OpenLibCLI)
"@
    Set-Content -Path "$INSTALL_DIR/examples/CMakeLists.txt" -Value $examplesCmake -Encoding ascii

    # Copy LICENSE, README, and version
    Copy-Item LICENSE $INSTALL_DIR
    Copy-Item README.md $INSTALL_DIR
    Copy-Item version $INSTALL_DIR

    Write-Host "CMake source package ready at $PWD/$INSTALL_DIR"
    Write-Host ""
    Write-Host "Consumer usage:"
    Write-Host "  cmake -B build -DCMAKE_PREFIX_PATH=/path/to/install/$PKG_NAME"
    Write-Host "  find_package(OpenLibCLI $VERSION REQUIRED)"
    Write-Host "  target_link_libraries(myapp PRIVATE OpenLibCLI::OpenLibCLI)"

    popd
    exit 0
} catch {
    Write-Host "Error: $_"
    popd
    exit 1
}
