#!/usr/bin/env bash
# package_cmake.sh — Create the source-only CMake package (microlog-style).
# Package name: OpenLibCLI-<version>-cmake
# Output layout:
#   install/OpenLibCLI-<version>-cmake/
#     include/OpenLibCLI/          <- public headers
#     lib/cmake/OpenLibCLI/        <- Config, ConfigVersion files
#     share/OpenLibCLI/src/        <- source files
#     examples/                    <- reference examples
#     LICENSE, README.md, version

set -euo pipefail
cd "$(dirname "$0")/../.."

if [ ! -f version ]; then
  echo "Error: version file not found"
  exit 1
fi

VERSION=$(tr -d '[:space:]' < version)
PKG_NAME="OpenLibCLI-$VERSION-cmake"
INSTALL_DIR="install/$PKG_NAME"
rm -rf "$INSTALL_DIR"
mkdir -p "$INSTALL_DIR/include/OpenLibCLI/config"
mkdir -p "$INSTALL_DIR/lib/cmake/OpenLibCLI"
mkdir -p "$INSTALL_DIR/share/OpenLibCLI/src/config"

# Headers (flatten to include/OpenLibCLI/, config subdir)
for f in cli/*.h; do
  [ -f "$f" ] && cp "$f" "$INSTALL_DIR/include/OpenLibCLI/"
done
cp cli/config/cli_config.h "$INSTALL_DIR/include/OpenLibCLI/config/" 2>/dev/null || true

# Sources
for f in cli/*.c; do
  [ -f "$f" ] && cp "$f" "$INSTALL_DIR/share/OpenLibCLI/src/"
done
cp cli/config/cli_embedded_config.h "$INSTALL_DIR/share/OpenLibCLI/src/config/" 2>/dev/null || true

# CMake config files
cat > "$INSTALL_DIR/lib/cmake/OpenLibCLI/openlibcliConfig.cmake" << 'CMKCFG'
# Generated by package_cmake.sh
get_filename_component(_OPENLIBCLI_DIR "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

add_library(OpenLibCLI STATIC
    "${_OPENLIBCLI_DIR}/share/OpenLibCLI/src/cli.c"
)
target_include_directories(OpenLibCLI PUBLIC "${_OPENLIBCLI_DIR}/include/OpenLibCLI")

if(WIN32)
    target_link_libraries(OpenLibCLI PUBLIC ws2_32)
endif()

add_library(OpenLibCLI::OpenLibCLI ALIAS OpenLibCLI)
check_required_components(OpenLibCLI)
CMKCFG

cat > "$INSTALL_DIR/lib/cmake/OpenLibCLI/openlibcliConfigVersion.cmake" << CMKVER
# Generated by package_cmake.sh
set(PACKAGE_VERSION "$VERSION")

if("\${PACKAGE_FIND_VERSION}" VERSION_EQUAL "${VERSION}")
  set(PACKAGE_VERSION_EXACT TRUE)
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
endif()

if("\${PACKAGE_FIND_VERSION}" VERSION_LESS "${VERSION}")
  string(REGEX MATCH "^[0-9]+" _ver_major "${VERSION}")
  if("\${PACKAGE_FIND_VERSION_MAJOR}" EQUAL "\${_ver_major}")
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
  endif()
endif()
CMKVER

# Copy examples
mkdir -p "$INSTALL_DIR/examples/shared"
mkdir -p "$INSTALL_DIR/examples/win_linux/serial"
mkdir -p "$INSTALL_DIR/examples/win_linux/telnet"
cp examples/shared/* "$INSTALL_DIR/examples/shared/" 2>/dev/null || true
cp examples/win_linux/serial/* "$INSTALL_DIR/examples/win_linux/serial/" 2>/dev/null || true
cp examples/win_linux/telnet/* "$INSTALL_DIR/examples/win_linux/telnet/" 2>/dev/null || true

cat > "$INSTALL_DIR/examples/CMakeLists.txt" << 'EXCFG'
cmake_minimum_required(VERSION 3.14)
project(OpenLibCLI-examples C)
set(CMAKE_C_STANDARD 99)
set(CMAKE_C_STANDARD_REQUIRED ON)

find_package(OpenLibCLI REQUIRED)

add_executable(cli_server_serial
    win_linux/serial/cli_server_serial.c
    win_linux/serial/cli_transport_serial.c
    shared/cli_demo_setup.c
)
target_link_libraries(cli_server_serial PRIVATE OpenLibCLI::OpenLibCLI)

add_executable(cli_server_telnet
    win_linux/telnet/cli_server_telnet.c
    win_linux/telnet/cli_transport_telnet.c
    shared/cli_demo_setup.c
)
target_link_libraries(cli_server_telnet PRIVATE OpenLibCLI::OpenLibCLI)
EXCFG

cp LICENSE README.md version "$INSTALL_DIR/" 2>/dev/null || true

echo "CMake source package ready at $(pwd)/$INSTALL_DIR"
echo ""
echo "Consumer usage:"
echo "  cmake -B build -DCMAKE_PREFIX_PATH=$(pwd)/$INSTALL_DIR"
echo "  find_package(OpenLibCLI $VERSION REQUIRED)"
echo "  target_link_libraries(myapp PRIVATE OpenLibCLI::OpenLibCLI)"
